---
- name: Configure Additional Content Credentials
  hosts: satellite
  gather_facts: false
  collections:
    - redhat.satellite
  tags: repositories

  vars_files:
    - group_vars/all.yml
    - satellite_config/external_repositories.yml

  tasks:
    - name: Ensure local files directory exists
      ansible.builtin.file:
        path: "{{ playbook_dir }}/files"
        state: directory
        mode: '0755'
      delegate_to: localhost

    - name: Download AlmaLinux 9 GPG key
      ansible.builtin.get_url:
        url: "https://repo.almalinux.org/almalinux/RPM-GPG-KEY-AlmaLinux-9"
        dest: "{{ playbook_dir }}/files/RPM-GPG-KEY-AlmaLinux-9"
        mode: '0644'
      delegate_to: localhost

    - name: "Create AlmaLinux GPG key"
      redhat.satellite.content_credential:
        server_url: "{{ satellite_server_url }}"
        username: "{{ satellite_username }}"
        password: "{{ satellite_password }}"
        validate_certs: "{{ satellite_validate_certs }}"
        organization: "{{ satellite_manifest_org }}"
        name: "AlmaLinux RPM-GPG-KEY"
        content_type: gpg_key
        content: "{{ lookup('file', playbook_dir + '/files/RPM-GPG-KEY-AlmaLinux-9') }}"
