---
- name: Configure External Repositories in Satellite
  hosts: satellite
  gather_facts: false
  collections:
    - redhat.satellite
  tags: repositories

  vars_files:
    - group_vars/all.yml
    - satellite_config/external_repositories.yml

  tasks:
    - name: Create or update external repositories
      redhat.satellite.repository:
        server_url: "{{ satellite_server_url }}"
        username: "{{ satellite_username }}"
        password: "{{ satellite_password }}"
        validate_certs: "{{ satellite_validate_certs }}"
        organization: "{{ satellite_manifest_org }}"
        product: "{{ item.product }}"
        name: "{{ item.name }}"
        label: "{{ item.label }}"
        content_type: "{{ item.content_type }}"
        arch: "{{ item.arch }}"
        url: "{{ item.url }}"
        gpg_key: "{{ item.gpg_key }}"
        download_policy: "{{ item.download_policy }}"
        mirroring_policy: "{{ item.mirroring_policy }}"
        state: "{{ item.state }}"
      loop: "{{ external_repositories }}"
      loop_control:
        label: "{{ item.name }}"
      tags: repositories
      register: external_repo_result

    - name: Synchronize external repositories
      redhat.satellite.repository_sync:
        server_url: "{{ satellite_server_url }}"
        username: "{{ satellite_username }}"
        password: "{{ satellite_password }}"
        validate_certs: "{{ satellite_validate_certs }}"
        organization: "{{ satellite_manifest_org }}"
        product: "{{ item.product }}"
        repository: "{{ item.name }}"
      loop: "{{ external_repositories }}"
      loop_control:
        label: "{{ item.name }}"
      async: 999999
      poll: 0
      register: external_sync_jobs
      tags: repositories

    - name: Wait for external repository synchronization to complete
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: external_sync_result
      until: external_sync_result.finished
      retries: 300
      delay: 30
      loop: "{{ external_sync_jobs.results }}"
      loop_control:
        label: "Syncing external repositories"
      when: external_sync_jobs.results is defined
      tags: repositories
