---
- name: Publish and Promote Content Views
  hosts: satellite
  gather_facts: false
  collections:
    - redhat.satellite
  tags: publish_promote
  vars_files:
    - group_vars/all.yml
    - satellite_config/content_views.yml
    - satellite_config/lifecycle_environments.yml
  vars:
    # All content views (both regular and composite) to publish to Library
    all_content_views: "{{ content_views | map(attribute='name') | list }}"

    # Only composite content views to promote to Development
    composite_content_views: "{{ content_views | selectattr('composite', 'defined') | selectattr('composite', 'equalto', true) | map(attribute='name') | list }}"

  tasks:
    - name: Publish ALL Content Views to Library (regular and composite)
      redhat.satellite.content_view_version:
        server_url: "{{ satellite_server_url }}"
        username: "{{ satellite_username }}"
        password: "{{ satellite_password }}"
        validate_certs: "{{ satellite_validate_certs }}"
        organization: "{{ satellite_manifest_org }}"
        content_view: "{{ item }}"
        description: "Published by Ansible on {{ ansible_date_time.iso8601 }}"
      loop: "{{ all_content_views }}"
      loop_control:
        label: "Publishing {{ item }} to Library"
      register: publish_results
      tags: publish

    - name: Promote COMPOSITE Content Views to Development only
      redhat.satellite.content_view_version:
        server_url: "{{ satellite_server_url }}"
        username: "{{ satellite_username }}"
        password: "{{ satellite_password }}"
        validate_certs: "{{ satellite_validate_certs }}"
        organization: "{{ satellite_manifest_org }}"
        content_view: "{{ item.0 }}"
        current_lifecycle_environment: "{{ item.1.prior }}"
        lifecycle_environments:
          - "{{ item.1.name }}"
        state: present
      with_nested:
        - "{{ composite_content_views }}"
        - "{{ lifecycle_environments | selectattr('name', 'equalto', 'Development') | list }}"
      loop_control:
        label: "Promoting {{ item.0 }} -> {{ item.1.name }}"
      tags: promote
